import { StockInput } from '../customStocks';
import { ShareType } from '../types/ShareType';

export const customCoinsToWatchList: StockInput[] = [
  {
    code: 'stellar',
    name: 'Stellar',
    attractivePriceUberLow: 0.32,
    attractivePriceStart: 0.496,
    url: 'https://www.coingecko.com/pl/waluty/stellar',
    type: ShareType.Coin,
  },
  {
    code: 'polygon-ecosystem-token',
    name: 'POL (ex-MATIC) (POL)',
    attractivePriceUberLow: 1.21,
    attractivePriceStart: 1.6,
    url: 'https://www.coingecko.com/pl/waluty/pol-ex-matic',
    type: ShareType.Coin,
  },
  {
    code: 'eos',
    name: 'EOS (EOS)',
    attractivePriceUberLow: 2,
    attractivePriceStart: 2.4,
    url: 'https://www.coingecko.com/pl/waluty/eos',
    type: ShareType.Coin,
  },
  {
    code: 'stepn',
    name: 'GMT',
    attractivePriceUberLow: 0.37,
    attractivePriceStart: 0.6,
    url: 'https://www.coingecko.com/pl/waluty/stepn',
    type: ShareType.Coin,
  },
  {
    code: 'book-of-meme',
    name: 'BOOK OF MEME (BOME)',
    attractivePriceUberLow: 0.02,
    attractivePriceStart: 0.024,
    url: 'https://www.coingecko.com/pl/waluty/book-of-meme',
    type: ShareType.Coin,
  },
  {
    code: 'litecoin',
    name: 'Litecoin',
    attractivePriceUberLow: 200,
    attractivePriceStart: 320,
    url: 'https://www.coingecko.com/pl/waluty/litecoin',
    type: ShareType.Coin,
  },
  {
    code: 'shiba-inu',
    name: 'Shiba Inu',
    attractivePriceUberLow: 0.00005,
    attractivePriceStart: 0.00006,
    url: 'https://www.coingecko.com/pl/waluty/shiba-inu',
    type: ShareType.Coin,
  },
  {
    code: 'bio-protocol',
    name: 'Bio Protocol',
    attractivePriceUberLow: 1.5,
    attractivePriceStart: 1.6,
    url: 'https://www.coingecko.com/pl/waluty/bio-protocol',
    type: ShareType.Coin,
  },
  {
    code: 'avalanche-2',
    name: 'Avalanche',
    attractivePriceUberLow: 39,
    attractivePriceStart: 80,
    url: 'https://www.coingecko.com/pl/waluty/avalanche',
    type: ShareType.Coin,
  },
  {
    code: 'aave',
    name: 'Aave',
    attractivePriceUberLow: 222,
    attractivePriceStart: 312,
    url: 'https://www.coingecko.com/pl/waluty/aave',
    type: ShareType.Coin,
  },
  {
    code: 'hedera-hashgraph',
    name: 'Hedera',
    attractivePriceUberLow: 0.17,
    attractivePriceStart: 0.256,
    url: 'https://www.coingecko.com/pl/waluty/hedera',
    type: ShareType.Coin,
  },
  {
    code: 'steem',
    name: 'Steem',
    attractivePriceUberLow: 0.72,
    attractivePriceStart: 0.8,
    url: 'https://www.coingecko.com/pl/waluty/steem',
    type: ShareType.Coin,
  },
  {
    code: 'chainlink',
    name: 'Chainlink',
    attractivePriceUberLow: 21,
    attractivePriceStart: 40,
    url: 'https://www.coingecko.com/pl/waluty/chainlink',
    type: ShareType.Coin,
  },
  {
    code: 'ethena',
    name: 'Ethena',
    attractivePriceUberLow: 1,
    attractivePriceStart: 5,
    url: 'https://www.coingecko.com/pl/waluty/ethena',
    type: ShareType.Coin,
  },
  {
    code: 'movement',
    name: 'Movement',
    attractivePriceUberLow: 2.5,
    attractivePriceStart: 2.76,
    url: 'https://www.coingecko.com/pl/waluty/movement',
    type: ShareType.Coin,
  },
  {
    code: 'arbitrum',
    name: 'Arbitrum',
    attractivePriceUberLow: 1.9,
    attractivePriceStart: 3.2,
    url: 'https://www.coingecko.com/pl/waluty/arbitrum',
    type: ShareType.Coin,
  },
  {
    code: 'tron',
    name: 'Tron',
    attractivePriceUberLow: 0.24,
    attractivePriceStart: 0.4,
    url: 'https://www.coingecko.com/pl/waluty/tron',
    type: ShareType.Coin,
  },
  {
    code: 'binance-coin-wormhole',
    name: 'Binance coin',
    attractivePriceStart: 2501,
    attractivePriceUberLow: 1932,
    url: 'https://www.coingecko.com/pl/waluty/bnb',
    type: ShareType.Coin,
  },
  {
    code: 'ethereum',
    name: 'Ethereum',
    attractivePriceStart: 7200,
    attractivePriceUberLow: 5736,
    url: 'https://www.coingecko.com/pl/waluty/ethereum',
    type: ShareType.Coin,
  },
  {
    code: 'pudgy-penguins',
    name: 'Pudgy Penguins',
    attractivePriceStart: 0.13,
    attractivePriceUberLow: 0.1,
    url: 'https://www.coingecko.com/pl/waluty/pudgy-penguins',
    type: ShareType.Coin,
  },
  {
    code: 'doge',
    name: 'Doge',
    attractivePriceStart: 1.55,
    attractivePriceUberLow: 1.3,
    url: 'https://www.coingecko.com/pl/waluty/dogecoin',
    type: ShareType.Coin,
  },
  {
    code: 'solana',
    name: 'Solana',
    attractivePriceStart: 616,
    attractivePriceUberLow: 558,
    url: 'https://www.coingecko.com/pl/waluty/solana',
    type: ShareType.Coin,
  },
  {
    code: 'pepe',
    name: 'Pepe',
    attractivePriceStart: 0.0000368,
    attractivePriceUberLow: 0.000042,
    url: 'https://www.coingecko.com/pl/waluty/pepe',
    type: ShareType.Coin,
  },
  {
    code: 'ada',
    name: 'Cardano',
    attractivePriceStart: 2.32,
    attractivePriceUberLow: 1.25,
    url: '',
    type: ShareType.Coin,
  },
  {
    code: 'dymension',
    name: 'Dymension',
    attractivePriceStart: 8,
    attractivePriceUberLow: 5,
    url: 'https://www.coingecko.com/pl/waluty/dymension',
    type: ShareType.Coin,
  },
  {
    code: 'render-token',
    name: 'Render token',
    attractivePriceStart: 24,
    attractivePriceUberLow: 6,
    url: 'https://www.coingecko.com/pl/waluty/render',
    type: ShareType.Coin,
  },
  {
    code: 'usual',
    name: 'Usual',
    attractivePriceStart: 2.4,
    attractivePriceUberLow: 2,
    url: 'https://www.coingecko.com/pl/waluty/usual',
    type: ShareType.Coin,
  },
  {
    code: 'thorchain',
    name: 'THORChain',
    attractivePriceStart: 20,
    attractivePriceUberLow: 3.5,
    url: 'https://www.coingecko.com/pl/waluty/thorchain',
    type: ShareType.Coin,
  },
  {
    code: 'bitcoin-cash',
    name: 'Bitcoin cash',
    attractivePriceStart: 1492,
    attractivePriceUberLow: 446,
    url: 'https://www.coingecko.com/pl/waluty/bitcoin-cash',
    type: ShareType.Coin,
  },
  {
    code: 'adventure-gold',
    name: 'Adventure gold',
    attractivePriceStart: 5.36,
    attractivePriceUberLow: 1.23,
    url: 'https://www.coingecko.com/pl/waluty/adventure-gold',
    type: ShareType.Coin,
  },
  {
    code: 'dogwifcoin',
    name: 'Dogwifcoin',
    attractivePriceStart: 8,
    attractivePriceUberLow: 5,
    url: 'https://www.coingecko.com/pl/waluty/dogwifhat',
    type: ShareType.Coin,
  },
];
