import { StockInput } from '../customStocks';
import { ShareType } from '../types/ShareType';

export const customStocksToWatchList: StockInput[] = [
  {
    code: 'SBUX',
    name: 'Starbucks',
    attractivePriceStart: 83,
    attractivePriceUberLow: 77,
    url: 'https://www.trading212.com/pl/trading-instruments/invest/SBUX.US',
    type: ShareType.Stock,
  },
  {
    code: 'IUSQ.DE',
    name: 'IShares MSCI ACWI (Acc)',
    attractivePriceStart: 84.5,
    attractivePriceUberLow: 80,
    url: 'https://www.trading212.com/pl/trading-instruments/invest/IUSQ.DE',
    type: ShareType.Stock,
  },
  {
    code: 'MCD',
    name: 'McDonalds',
    attractivePriceStart: 252.8,
    attractivePriceUberLow: 233,
    url: 'https://www.trading212.com/pl/trading-instruments/invest/MCD.US',
    type: ShareType.Stock,
  },
  {
    code: 'O',
    name: 'Realty Income',
    attractivePriceStart: 59.2,
    attractivePriceUberLow: 43,
    url: 'https://www.trading212.com/pl/trading-instruments/invest/O.US',
    type: ShareType.Stock,
  },
  {
    code: 'JNJ',
    name: 'Johnson & Johnson',
    attractivePriceStart: 150,
    attractivePriceUberLow: 145.5,
    url: 'https://www.trading212.com/pl/trading-instruments/invest/JNJ.US',
    type: ShareType.Stock,
  },
  {
    code: 'KO',
    name: 'Coca-Cola',
    attractivePriceStart: 56.8,
    attractivePriceUberLow: 53,
    url: 'https://www.trading212.com/pl/trading-instruments/invest/KO.US',
    type: ShareType.Stock,
  },
  {
    code: 'CSCO',
    name: 'Cisco',
    attractivePriceStart: 44,
    attractivePriceUberLow: 40,
    url: 'https://www.trading212.com/pl/trading-instruments/invest/CSCO.US',
    type: ShareType.Stock,
  },
  {
    code: 'BP.L',
    name: 'BP',
    attractivePriceStart: 448,
    attractivePriceUberLow: 430,
    url: 'https://www.trading212.com/pl/trading-instruments/invest/BP.GB',
    type: ShareType.Stock,
  },
  {
    code: 'PPG',
    name: 'PPG',
    attractivePriceStart: 120,
    attractivePriceUberLow: 111,
    url: 'https://www.trading212.com/pl/trading-instruments/invest/PPG.US',
    type: ShareType.Stock,
  },
];
